services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: solo
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-09-02T18-05-34Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

  api:
    build:
      context: ../../
      dockerfile: infra/docker/api.Dockerfile
    env_file:
      - ../../.env.example
    environment:
      PORT: 3000
    depends_on:
      - db
      - redis
      - minio
      - mailhog
    ports:
      - "3000:3000"

  web:
    build:
      context: ../../
      dockerfile: infra/docker/web.Dockerfile
    depends_on:
      - api
    ports:
      - "5173:5173"

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - api
      - web

volumes:
  db-data:
  minio-data:
